# This file contains the rest of your serving-components.yaml content
# Placeholder for your actual resources that depend on CRDs
apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: serving
    app.kubernetes.io/version: "1.5.0"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: knative-serving
  labels:
    app.kubernetes.io/name: knative-serving
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: "1.5.0"

# Add the rest of your resources here